### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by b3wii** [Klairm/LINUX-PS3-ISO-TOOLS#1]
LINUX-PS3-ISO-TOOLS$ ./setup.sh
Collecting pyqt5
  Downloading https://files.pythonhosted.org/packages/1d/31/896dc3dfb6c81c70164019a6cbba6ab037e3af7653d9ca60ccc874ee4c27/PyQt5-5.15.1.tar.gz (3.3MB)
    100% |████████████████████████████████| 3.3MB 344kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-38azi7hr/pyqt5/
chmod: cannot access 'ps3iso_utilities/*': No such file or directory
mv: cannot stat 'ps3iso_utilities/*': No such file or directory

**Comment by b3wii** [comment]
Also when i start it via python3 PS3_ISO_Tools.py and select an iso to extract nothing happens.

**Comment by Klairm** [comment]
About the setuptools error, is an depency error, you should install the python3-setuptools package, and about nothing happens, this is a bug that it doesn't show the status on the GUI but it actually works behind. I'm currently working on fix that, sorry for the issue and thanks for report

**Comment by Klairm** [comment]
Will fix this bug when I get some time, busy with studies now

**Comment by Klairm** [comment]
Fixed the issue, now the program will display on text the status of the process.
